import pandas as pd

configfile: "config/config.yaml"
report: "workflow/reports/workflow.rst"

vcfs = pd.read_table(config["vcfs"]).set_index("sample", drop=False)
samples = list(vcfs["sample"])
spims = ['spm','sim']

if config['spim'].lower() == 'combined':

    rule extract_spms:
        input:
            lambda wildcards: vcfs.loc[wildcards.sample]['spim']
        output:
            temp("resources/input/{sample}.spm.vcf.gz"),
        shadow: "full"
        envmodules:
            "bioinfo-tools",
            "vcftools/0.1.12"
        group: "separate_spims"
        shell:
            """
            vcftools --gzvcf {input} --remove-indels \
            --recode --recode-INFO-all --stdout |
            gzip -c > {output}
            """

    rule extract_sims:
        input:
            lambda wildcards: vcfs.loc[wildcards.sample]['spim']
        output:
            temp("resources/input/{sample}.sim.vcf.gz")
        shadow: "full"
        envmodules:
            "bioinfo-tools",
            "vcftools/0.1.12"
        group: "separate_spims"
        shell:
            """
            vcftools --gzvcf {input} --keep-only-indels \
            --recode --recode-INFO-all --stdout |
            gzip -c > {output}
            """

elif config['spim'].lower() == 'separated':

    rule link_vcfs:
        input:
            lambda wildcards: vcfs.loc[wildcards.sample][wildcards.spim]
        output:
            "resources/input/{sample}.{spim}.vcf.gz"
        resources:
            runtime_min=5
        shell:
            "mkdir -p resources/input ; ln -s {input} {output}"

rule snpEff:
    input:
        vcf = "resources/input/{sample}.{spim}.vcf.gz"
    output: 
        "results/annotation/snpEff/{sample}.{spim}.ann.vcf.gz"
    params:
        config["genome"]
    envmodules:
        "bioinfo-tools",
        "snpEff/4.3t"
    shell:
        """
        snpEff ann -noStats {params} {input.vcf} |
        gzip -c > {output}
        """

rule vcf2bed:
    input:
        expand("resources/input/{{sample}}.{spim}.vcf.gz", spim = spims)
    output:
        expand("results/input_beds/{{sample}}.{spim}.sorted.bed", spim = spims)
    envmodules:
        "bioinfo-tools",
        "BEDOPS/2.4.39"
    shell:
        "workflow/scripts/vcf2bed.sh {wildcards.sample} {input} {output}"

if config["phyloP_format"] == "bw":

    rule phyloP:
        input:
            bed = "results/input_beds/{sample}.{spim}.sorted.bed",
            phyloP = config["phyloP"]
        output:
            "results/annotation/phyloP/{sample}.{spim}.phyloP.bed"
        shadow: "full"
        shell:
            """
            mkdir -p results/annotation/ ; mkdir -p results/annotation/phyloP
            workflow/scripts/phylop_annotation_bw.sh {input.bed} {output} {input.phyloP}
            """

elif config["phyloP_format"] == "bed":

    with open(config['chrom_list']) as f:
        chromosomes = f.read().splitlines()

    rule split_chroms:
        input:  "results/input_beds/{sample}.{spim}.sorted.bed"
        output: temp("results/input_beds/{sample}.{spim}.sorted.{chrom}.bed")
        shell: 
            """
            awk -v chr='{wildcards.chrom}' -v OFS='\t' '$1==chr' {input} > {output}
            """

    rule phyloP:
        input: 
            bed = "results/input_beds/{sample}.{spim}.sorted.{chrom}.bed",
            phyloP = config['phyloP'] + "/" + "{chrom}.bed.gz"
        output: temp("results/annotation/phyloP/{sample}.{spim}.sorted.{chrom}.phyloP.bed")
        shell:
            """
            mkdir -p results/annotation/ ; mkdir -p results/annotation/phyloP
            bedtools intersect -a {input.bed} -b {input.phyloP} -loj -sorted |
                awk -F '\t' '{{OFS=FS}}{{if ($7 ==".") {{$8="NaN"}}}}1' |
                cut -f 1-4,9 > {output}
            """
    
    rule join_phyloP:
        input: 
            phylop = expand(["results/annotation/phyloP/{{sample}}.{{spim}}.sorted.{chrom}.phyloP.bed"], chrom = chromosomes),
            bed = "results/input_beds/{sample}.{spim}.sorted.bed"
        output: "results/annotation/phyloP/{sample}.{spim}.phyloP.bed"
        wildcard_constraints:                                                                                                                                                            
            spim = "s.m"
        shell:
            """
            workflow/scripts/join_phylop_scores.py --phylop '{input.phylop}' --bed {input.bed} --out {output}
            """

if config['spim'].lower() == 'separated':

    rule annotation_summary:
        input:
            spm_vcf = vcfs['spm'].tolist(),
            sim_vcf = vcfs['sim'].tolist(),
            spm_snpEff = expand(["results/annotation/snpEff/{sample}.spm.ann.vcf.gz"], sample = samples),
            sim_snpEff = expand(["results/annotation/snpEff/{sample}.sim.ann.vcf.gz"], sample = samples),
            spm_phyloP = expand(["results/annotation/phyloP/{sample}.spm.phyloP.bed"], sample = samples),
            sim_phyloP = expand(["results/annotation/phyloP/{sample}.sim.phyloP.bed"], sample = samples)
        output:
            "results/annotation/" + config["run_name"] + ".annotation_summary.tsv"
        envmodules:
            "python3/3.9.5"
        shell:
            """
            workflow/scripts/annotation_summary.py --samples '{samples}' \
            --spm_vcfs '{input.spm_vcf}' --sim_vcfs '{input.sim_vcf}' \
            --spm_anns '{input.spm_snpEff}' --sim_anns '{input.sim_snpEff}' \
            --spm_phylops '{input.spm_phyloP}' --sim_phylops '{input.sim_phyloP}' \
            --out {output}
            """


elif config['spim'].lower() == 'combined':

    rule annotation_summary:
        input:
            spim_vcf = vcfs['spim'].tolist(),
            spm_snpEff = expand("results/annotation/snpEff/{sample}.spm.ann.vcf.gz", sample = samples),
            sim_snpEff = expand("results/annotation/snpEff/{sample}.sim.ann.vcf.gz", sample = samples),
            spm_phyloP = expand("results/annotation/phyloP/{sample}.spm.phyloP.bed", sample = samples),
            sim_phyloP = expand("results/annotation/phyloP/{sample}.sim.phyloP.bed", sample = samples)
        output:
            "results/annotation/" + config["run_name"] + ".annotation_summary.tsv"
        envmodules:
            "python3/3.9.5"
        shell:
            """
            workflow/scripts/annotation_summary.py --samples '{samples}'' \
            --spim_vcfs '{input.spim_vcf}' \
            --spm_anns '{input.spm_snpEff}' --sim_anns '{input.sim_snpEff}' \
            --spm_phylops '{input.spm_phyloP}' --sim_phylops '{input.sim_phyloP}' \
            --out {output}
            """

rule annotate:
    input:
        "results/annotation/" + config['run_name'] + ".annotation_summary.tsv"

rule combine_data: 
    input:
        snpEff = "results/annotation/snpEff/{sample}.{spim}.ann.vcf.gz",
        phyloP = "results/annotation/phyloP/{sample}.{spim}.phyloP.bed"
    output:
        temp("results/composite_matrix/{sample}.{spim}.composite_matrix.tsv.gz")
    envmodules:
            "python3/3.9.5"
    shell:
        """
        workflow/scripts/composite_matrix.py --sample {wildcards.sample} \
        --ann {input.snpEff} --phylop {input.phyloP} \
        --out {output}
        """

rule combine_all_samples:
    input:
        expand("results/composite_matrix/{sample}.{spim}.composite_matrix.tsv.gz", sample = samples, spim = spims)
    output:
        "results/composite_matrix/" + config["run_name"] + ".composite_matrix.tsv.gz"
    shell:
        """
        for matrix in {input} ; do 
            if [ -f {output} ] ; then
                zcat "$matrix" | sed 1d | gzip -c >> {output}
            else
                zcat "$matrix" | gzip -c > {output}
            fi
        done
        """

rule composite_matrix:
    input:
        annotation = "results/annotation/" + config['run_name'] + ".annotation_summary.tsv",
        composite_matrix = "results/composite_matrix/" + config["run_name"] + ".composite_matrix.tsv.gz"

rule nccm_analysis:
    input:
        matrix = "results/composite_matrix/" + config["run_name"] + ".composite_matrix.tsv.gz",
        gene_set = config["gene_set"]
    output:
        "{params.prefix}.scan.tsv",
        "{params.prefix}.top_nccm_genes_spim.tsv",
        "{params.prefix}.top_nccm_genes.list"
    params:
        phyloP_threshold = config["phyloP_threshold"],
        prefix = "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"]
    threads: 16
    shell:
        """
        mkdir -p results/nccms ; \
        workflow/scripts/1.1.NCCM_analysis.sh {input.matrix} {input.gene_set} \
        {params.prefix} {params.phyloP_threshold} 10 7 {threads}
        """

rule all:
    input:
        "results/annotation/" + config['run_name'] + ".annotation_summary.tsv",
        "results/composite_matrix/" + config["run_name"] + ".composite_matrix.tsv.gz",
        "{params.prefix}.scan.tsv",
        "{params.prefix}.top_nccm_genes_spim.tsv",
        "{params.prefix}.top_nccm_genes.list"
    params:
        prefix = "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"]