# Run the NCCM analysis
def get_matrix_input(wildcards):
    """
    Returns the path to the matrix based on the 'start_from' config setting.
    """
    if config["start_from"] == "matrix":
        # Use the pre-existing matrix file
        return config["matrix_path"]
    elif config["start_from"] == "vcf":
        # Use the matrix that will be generated by the workflow
        return "results/composite_matrix/" + config["run_name"] + ".composite_matrix.tsv.gz"
    else:
        raise ValueError("ConfigError: 'start_from' must be 'vcf' or 'matrix'")

rule nccm_analysis:
    input:
        matrix = get_matrix_input,
        gene_set = config["gene_set"]
    output:
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".scan.tsv",
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".top_nccm_genes_spim.tsv",
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".top_nccm_genes.list"
    params:
        phyloP_threshold = config["phyloP_threshold"],
        prefix = "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"]
    threads: config["threads"]
    shell:
        """
        mkdir -p results/nccms ; \
        workflow/scripts/1.1.NCCM_analysis.sh {input.matrix} {input.gene_set} \
        {params.prefix} {params.phyloP_threshold} 10 7 {threads}
        """

rule nccms:
    input:
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".scan.tsv",
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".top_nccm_genes_spim.tsv",
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".top_nccm_genes.list"
    params:
        prefix = "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"]