def get_matrix_input(wildcards):
    """
    Returns the path to the matrix based on the 'start_from' config setting.
    """
    if config["start_from"] == "matrix":
        # Use the pre-existing matrix file
        return config["matrix_path"]
    elif config["start_from"] == "vcf":
        # Use the matrix that will be generated by the workflow
        return "results/composite_matrix/" + config["run_name"] + ".composite_matrix.tsv.gz"
    else:
        raise ValueError("ConfigError: 'start_from' must be 'vcf' or 'matrix'")

rule noncoding_bed:
    input:
        matrix = get_matrix_input
    output:
        temp("results/nccms/" + config["run_name"] + ".ncm.bed")
    shell:
        """
        zcat {input} | sed 1d | awk '$7=="noncoding"' | 
        awk -v OFS='\t' -v FS='\t' '{{print $1,$8,$9,$10,$5}}' \
        > {output}
        """

rule nccm_analysis:
    input:
        ncm = "results/nccms/" + config["run_name"] + ".ncm.bed",
        gene_set = config["gene_set"]
    output:
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".scan.tsv",
    params:
        phyloP_threshold = config["phyloP_threshold"],
    threads: config["threads"]
    shell:
        """
        mkdir -p results/nccms ; \
        workflow/scripts/nccm_analysis.sh {input.ncm} {input.gene_set} \
        {params.phyloP_threshold} {output}
        """

rule nccms:
    input:
        "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"] + ".scan.tsv",
    params:
        prefix = "results/nccms/" + config["run_name"] + ".phylop-" + config["phyloP_threshold"]