run_name: "hg19_test"
start_from: "vcf"
matrix_path: "/proj/sens2017503/nobackup/12_pancancer_RP/2_pancancer_rerun/0_pipeline_test/hello_compisite_matrix.tsv.gz"
vcfs: "config/example.input.tsv"
spim: "separated"
genome: "GRCh37.75"
phyloP: "/proj/nobackup/sens2017503/4_Phase_II_GBM/5_NCCM_analysis/pipeline_test/pipe-those-NCCMs/resources/phylop_links"
phyloP_format: "bed"
phyloP_threshold: "1.2"
chrom_list: "resources/hg19.chromosomes.txt"
gene_set: "/proj/sens2017503/nobackup/12_pancancer_RP/1_new_flanks_file/a_create/hg19_gene_100kb_flanks.bed"
coding_bed: "/proj/sens2017503/nobackup/12_pancancer_RP/1_new_flanks_file/b_constraint_counts/hg19.coding_regions.bed"
ref_fasta: "/proj/sens2017503/nobackup/12_pancancer_RP/2_pancancer_rerun/0_pipeline_test/human_g1k_v37.chrs.fasta"
qc_bed: "/proj/sens2017503/nobackup/12_pancancer_RP/1_new_flanks_file/e_gene_filtering/2_mappability/k100.umap.lt1.sorted.merged.bed.gz"
threads: 16